package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

// ─── Rendering ───────────────────────────────────────────────────────────────

// renderAll generates all output files defined in outputTargets().
func renderAll(root string, k Knowledge) {
	for _, t := range outputTargets() {
		renderFile(root, t.Path, t.Template, k)
	}
}

// renderFile executes a template and writes the result to a file.
func renderFile(root, relPath string, tmplStr string, data Knowledge) {
	funcMap := template.FuncMap{
		"join":  strings.Join,
		"lower": strings.ToLower,
	}
	t := template.Must(template.New(relPath).Funcs(funcMap).Parse(tmplStr))
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		fmt.Fprintf(os.Stderr, "error rendering %s: %v\n", relPath, err)
		os.Exit(1)
	}

	outPath := filepath.Join(root, relPath)
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "error creating dir for %s: %v\n", relPath, err)
		os.Exit(1)
	}
	if err := os.WriteFile(outPath, buf.Bytes(), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", relPath, err)
		os.Exit(1)
	}
}

// writeKnowledgeYAML serializes the knowledge model to knowledge.yaml.
func writeKnowledgeYAML(root string, k Knowledge) {
	var buf bytes.Buffer
	buf.WriteString("# Generated by make docs-gen — DO NOT EDIT\n")
	buf.WriteString("# Source: hack/gen-ai-docs/\n")
	buf.WriteString("# Regenerate: make docs-gen\n\n")

	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(k); err != nil {
		fmt.Fprintf(os.Stderr, "error encoding knowledge.yaml: %v\n", err)
		os.Exit(1)
	}
	if err := enc.Close(); err != nil {
		fmt.Fprintf(os.Stderr, "error closing encoder: %v\n", err)
		os.Exit(1)
	}

	outPath := filepath.Join(root, "knowledge.yaml")
	if err := os.WriteFile(outPath, buf.Bytes(), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing knowledge.yaml: %v\n", err)
		os.Exit(1)
	}
}

// ─── File Helpers ────────────────────────────────────────────────────────────

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func readFileStr(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	return string(data)
}

func parseGoMod(path string) (goVersion, module string) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "1.23", "github.com/corewire/drop"
	}
	goVersion = "1.23"
	for _, line := range strings.Split(string(data), "\n") {
		if strings.HasPrefix(line, "go ") {
			goVersion = strings.TrimSpace(strings.TrimPrefix(line, "go "))
		}
		if strings.HasPrefix(line, "module ") {
			module = strings.TrimSpace(strings.TrimPrefix(line, "module "))
		}
	}
	return goVersion, module
}
