apiVersion: drop.corewire.io/v1alpha1
kind: PullPolicy
metadata:
  labels:
    app.kubernetes.io/name: drop
    app.kubernetes.io/managed-by: kustomize
  name: pullpolicy-sample
spec:
  # TODO(user): Add fields here
