apiVersion: drop.corewire.io/v1alpha1
kind: PullPolicy
metadata:
  name: default
spec:
  maxConcurrentNodes: 2
  minDelayBetweenPulls: 5s
  repullInterval: 1h
  failureBackoff:
    initial: 30s
    max: 5m
