apiVersion: drop.corewire.io/v1alpha1
kind: CachedImageSet
metadata:
  name: core-images
spec:
  policyRef:
    name: default
  images:
    - image: docker.io/library/alpine
      tag: "3.19"
    - image: docker.io/library/busybox
      tag: "1.36"
    - image: docker.io/library/redis
      tag: "7-alpine"
