apiVersion: drop.corewire.io/v1alpha1
kind: CachedImage
metadata:
  name: nginx
spec:
  image: docker.io/library/nginx
  tag: "1.25-alpine"
  policyRef:
    name: default
  nodeSelector:
    kubernetes.io/arch: amd64
