## Append samples of your project ##
resources:
- puller_v1alpha1_cachedimage.yaml
- puller_v1alpha1_cachedimageset.yaml
- puller_v1alpha1_pullpolicy.yaml
- puller_v1alpha1_discoverypolicy.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
