//go:build !ignore_autogenerated

/*
Copyright (c) 2026 Breee

SPDX-License-Identifier: MIT
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AggregateSignalConfig) DeepCopyInto(out *AggregateSignalConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AggregateSignalConfig.
func (in *AggregateSignalConfig) DeepCopy() *AggregateSignalConfig {
	if in == nil {
		return nil
	}
	out := new(AggregateSignalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackoffConfig) DeepCopyInto(out *BackoffConfig) {
	*out = *in
	out.Initial = in.Initial
	out.Max = in.Max
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackoffConfig.
func (in *BackoffConfig) DeepCopy() *BackoffConfig {
	if in == nil {
		return nil
	}
	out := new(BackoffConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachedImage) DeepCopyInto(out *CachedImage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachedImage.
func (in *CachedImage) DeepCopy() *CachedImage {
	if in == nil {
		return nil
	}
	out := new(CachedImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CachedImage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachedImageList) DeepCopyInto(out *CachedImageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CachedImage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachedImageList.
func (in *CachedImageList) DeepCopy() *CachedImageList {
	if in == nil {
		return nil
	}
	out := new(CachedImageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CachedImageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachedImageSet) DeepCopyInto(out *CachedImageSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachedImageSet.
func (in *CachedImageSet) DeepCopy() *CachedImageSet {
	if in == nil {
		return nil
	}
	out := new(CachedImageSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CachedImageSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachedImageSetList) DeepCopyInto(out *CachedImageSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CachedImageSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachedImageSetList.
func (in *CachedImageSetList) DeepCopy() *CachedImageSetList {
	if in == nil {
		return nil
	}
	out := new(CachedImageSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CachedImageSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachedImageSetSpec) DeepCopyInto(out *CachedImageSetSpec) {
	*out = *in
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(PolicyReference)
		**out = **in
	}
	if in.DiscoveryPolicyRef != nil {
		in, out := &in.DiscoveryPolicyRef, &out.DiscoveryPolicyRef
		*out = new(DiscoveryPolicyReference)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = make([]ImageEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachedImageSetSpec.
func (in *CachedImageSetSpec) DeepCopy() *CachedImageSetSpec {
	if in == nil {
		return nil
	}
	out := new(CachedImageSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachedImageSetStatus) DeepCopyInto(out *CachedImageSetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachedImageSetStatus.
func (in *CachedImageSetStatus) DeepCopy() *CachedImageSetStatus {
	if in == nil {
		return nil
	}
	out := new(CachedImageSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachedImageSpec) DeepCopyInto(out *CachedImageSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(PolicyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachedImageSpec.
func (in *CachedImageSpec) DeepCopy() *CachedImageSpec {
	if in == nil {
		return nil
	}
	out := new(CachedImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachedImageStatus) DeepCopyInto(out *CachedImageStatus) {
	*out = *in
	if in.CachedNodes != nil {
		in, out := &in.CachedNodes, &out.CachedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastPulledAt != nil {
		in, out := &in.LastPulledAt, &out.LastPulledAt
		*out = (*in).DeepCopy()
	}
	if in.LastAttemptedAt != nil {
		in, out := &in.LastAttemptedAt, &out.LastAttemptedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachedImageStatus.
func (in *CachedImageStatus) DeepCopy() *CachedImageStatus {
	if in == nil {
		return nil
	}
	out := new(CachedImageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredImage) DeepCopyInto(out *DiscoveredImage) {
	*out = *in
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]ImageSignalValue, len(*in))
		copy(*out, *in)
	}
	if in.Ranking != nil {
		in, out := &in.Ranking, &out.Ranking
		*out = new(ImageRankingDetail)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredImage.
func (in *DiscoveredImage) DeepCopy() *DiscoveredImage {
	if in == nil {
		return nil
	}
	out := new(DiscoveredImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryLokiQuery) DeepCopyInto(out *DiscoveryLokiQuery) {
	*out = *in
	if in.Lookback != nil {
		in, out := &in.Lookback, &out.Lookback
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Parser != nil {
		in, out := &in.Parser, &out.Parser
		*out = new(LokiParser)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryLokiQuery.
func (in *DiscoveryLokiQuery) DeepCopy() *DiscoveryLokiQuery {
	if in == nil {
		return nil
	}
	out := new(DiscoveryLokiQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryPolicy) DeepCopyInto(out *DiscoveryPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryPolicy.
func (in *DiscoveryPolicy) DeepCopy() *DiscoveryPolicy {
	if in == nil {
		return nil
	}
	out := new(DiscoveryPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscoveryPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryPolicyList) DeepCopyInto(out *DiscoveryPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiscoveryPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryPolicyList.
func (in *DiscoveryPolicyList) DeepCopy() *DiscoveryPolicyList {
	if in == nil {
		return nil
	}
	out := new(DiscoveryPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscoveryPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryPolicyReference) DeepCopyInto(out *DiscoveryPolicyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryPolicyReference.
func (in *DiscoveryPolicyReference) DeepCopy() *DiscoveryPolicyReference {
	if in == nil {
		return nil
	}
	out := new(DiscoveryPolicyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryPolicySpec) DeepCopyInto(out *DiscoveryPolicySpec) {
	*out = *in
	if in.Queries != nil {
		in, out := &in.Queries, &out.Queries
		*out = make([]DiscoveryQuery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]DiscoverySignal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ranking != nil {
		in, out := &in.Ranking, &out.Ranking
		*out = new(DiscoveryRanking)
		(*in).DeepCopyInto(*out)
	}
	out.SyncInterval = in.SyncInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryPolicySpec.
func (in *DiscoveryPolicySpec) DeepCopy() *DiscoveryPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DiscoveryPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryPolicyStatus) DeepCopyInto(out *DiscoveryPolicyStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.QueryResults != nil {
		in, out := &in.QueryResults, &out.QueryResults
		*out = make([]QueryResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SignalResults != nil {
		in, out := &in.SignalResults, &out.SignalResults
		*out = make([]SignalResult, len(*in))
		copy(*out, *in)
	}
	if in.DiscoveredImages != nil {
		in, out := &in.DiscoveredImages, &out.DiscoveredImages
		*out = make([]DiscoveredImage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryPolicyStatus.
func (in *DiscoveryPolicyStatus) DeepCopy() *DiscoveryPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DiscoveryPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryPrometheusQuery) DeepCopyInto(out *DiscoveryPrometheusQuery) {
	*out = *in
	if in.Lookback != nil {
		in, out := &in.Lookback, &out.Lookback
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Step != nil {
		in, out := &in.Step, &out.Step
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryPrometheusQuery.
func (in *DiscoveryPrometheusQuery) DeepCopy() *DiscoveryPrometheusQuery {
	if in == nil {
		return nil
	}
	out := new(DiscoveryPrometheusQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryQuery) DeepCopyInto(out *DiscoveryQuery) {
	*out = *in
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(DiscoveryPrometheusQuery)
		(*in).DeepCopyInto(*out)
	}
	if in.Loki != nil {
		in, out := &in.Loki, &out.Loki
		*out = new(DiscoveryLokiQuery)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryQuery.
func (in *DiscoveryQuery) DeepCopy() *DiscoveryQuery {
	if in == nil {
		return nil
	}
	out := new(DiscoveryQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryRanking) DeepCopyInto(out *DiscoveryRanking) {
	*out = *in
	if in.Signal != nil {
		in, out := &in.Signal, &out.Signal
		*out = new(SignalRankingConfig)
		**out = **in
	}
	if in.WeightedSum != nil {
		in, out := &in.WeightedSum, &out.WeightedSum
		*out = new(WeightedSumRankingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ModelExposure != nil {
		in, out := &in.ModelExposure, &out.ModelExposure
		*out = new(ModelExposureRankingConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryRanking.
func (in *DiscoveryRanking) DeepCopy() *DiscoveryRanking {
	if in == nil {
		return nil
	}
	out := new(DiscoveryRanking)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoverySignal) DeepCopyInto(out *DiscoverySignal) {
	*out = *in
	if in.Aggregate != nil {
		in, out := &in.Aggregate, &out.Aggregate
		*out = new(AggregateSignalConfig)
		**out = **in
	}
	if in.TimeWeightedAggregate != nil {
		in, out := &in.TimeWeightedAggregate, &out.TimeWeightedAggregate
		*out = new(TimeWeightedAggregateSignalConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.WindowAggregate != nil {
		in, out := &in.WindowAggregate, &out.WindowAggregate
		*out = new(WindowAggregateSignalConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EventPullTime != nil {
		in, out := &in.EventPullTime, &out.EventPullTime
		*out = new(EventPullTimeSignalConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoverySignal.
func (in *DiscoverySignal) DeepCopy() *DiscoverySignal {
	if in == nil {
		return nil
	}
	out := new(DiscoverySignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventPullTimeSignalConfig) DeepCopyInto(out *EventPullTimeSignalConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventPullTimeSignalConfig.
func (in *EventPullTimeSignalConfig) DeepCopy() *EventPullTimeSignalConfig {
	if in == nil {
		return nil
	}
	out := new(EventPullTimeSignalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageEntry) DeepCopyInto(out *ImageEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageEntry.
func (in *ImageEntry) DeepCopy() *ImageEntry {
	if in == nil {
		return nil
	}
	out := new(ImageEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageRankingDetail) DeepCopyInto(out *ImageRankingDetail) {
	*out = *in
	if in.Terms != nil {
		in, out := &in.Terms, &out.Terms
		*out = make([]RankingTerm, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageRankingDetail.
func (in *ImageRankingDetail) DeepCopy() *ImageRankingDetail {
	if in == nil {
		return nil
	}
	out := new(ImageRankingDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSignalValue) DeepCopyInto(out *ImageSignalValue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSignalValue.
func (in *ImageSignalValue) DeepCopy() *ImageSignalValue {
	if in == nil {
		return nil
	}
	out := new(ImageSignalValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LokiParser) DeepCopyInto(out *LokiParser) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LokiParser.
func (in *LokiParser) DeepCopy() *LokiParser {
	if in == nil {
		return nil
	}
	out := new(LokiParser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelExposureRankingConfig) DeepCopyInto(out *ModelExposureRankingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelExposureRankingConfig.
func (in *ModelExposureRankingConfig) DeepCopy() *ModelExposureRankingConfig {
	if in == nil {
		return nil
	}
	out := new(ModelExposureRankingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyReference) DeepCopyInto(out *PolicyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyReference.
func (in *PolicyReference) DeepCopy() *PolicyReference {
	if in == nil {
		return nil
	}
	out := new(PolicyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullPolicy) DeepCopyInto(out *PullPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullPolicy.
func (in *PullPolicy) DeepCopy() *PullPolicy {
	if in == nil {
		return nil
	}
	out := new(PullPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PullPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullPolicyList) DeepCopyInto(out *PullPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PullPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullPolicyList.
func (in *PullPolicyList) DeepCopy() *PullPolicyList {
	if in == nil {
		return nil
	}
	out := new(PullPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PullPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullPolicySpec) DeepCopyInto(out *PullPolicySpec) {
	*out = *in
	out.MinDelayBetweenPulls = in.MinDelayBetweenPulls
	if in.FailureBackoff != nil {
		in, out := &in.FailureBackoff, &out.FailureBackoff
		*out = new(BackoffConfig)
		**out = **in
	}
	if in.RepullInterval != nil {
		in, out := &in.RepullInterval, &out.RepullInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullPolicySpec.
func (in *PullPolicySpec) DeepCopy() *PullPolicySpec {
	if in == nil {
		return nil
	}
	out := new(PullPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryResult) DeepCopyInto(out *QueryResult) {
	*out = *in
	if in.Series != nil {
		in, out := &in.Series, &out.Series
		*out = new(int32)
		**out = **in
	}
	if in.Samples != nil {
		in, out := &in.Samples, &out.Samples
		*out = new(int64)
		**out = **in
	}
	if in.Records != nil {
		in, out := &in.Records, &out.Records
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryResult.
func (in *QueryResult) DeepCopy() *QueryResult {
	if in == nil {
		return nil
	}
	out := new(QueryResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RankingTerm) DeepCopyInto(out *RankingTerm) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RankingTerm.
func (in *RankingTerm) DeepCopy() *RankingTerm {
	if in == nil {
		return nil
	}
	out := new(RankingTerm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignalRankingConfig) DeepCopyInto(out *SignalRankingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignalRankingConfig.
func (in *SignalRankingConfig) DeepCopy() *SignalRankingConfig {
	if in == nil {
		return nil
	}
	out := new(SignalRankingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignalResult) DeepCopyInto(out *SignalResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignalResult.
func (in *SignalResult) DeepCopy() *SignalResult {
	if in == nil {
		return nil
	}
	out := new(SignalResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeOfDayWindow) DeepCopyInto(out *TimeOfDayWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeOfDayWindow.
func (in *TimeOfDayWindow) DeepCopy() *TimeOfDayWindow {
	if in == nil {
		return nil
	}
	out := new(TimeOfDayWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeWeightedAggregateSignalConfig) DeepCopyInto(out *TimeWeightedAggregateSignalConfig) {
	*out = *in
	out.DefaultWeight = in.DefaultWeight.DeepCopy()
	if in.Windows != nil {
		in, out := &in.Windows, &out.Windows
		*out = make([]TimeWeightedWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeWeightedAggregateSignalConfig.
func (in *TimeWeightedAggregateSignalConfig) DeepCopy() *TimeWeightedAggregateSignalConfig {
	if in == nil {
		return nil
	}
	out := new(TimeWeightedAggregateSignalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeWeightedWindow) DeepCopyInto(out *TimeWeightedWindow) {
	*out = *in
	out.Weight = in.Weight.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeWeightedWindow.
func (in *TimeWeightedWindow) DeepCopy() *TimeWeightedWindow {
	if in == nil {
		return nil
	}
	out := new(TimeWeightedWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeightedSumRankingConfig) DeepCopyInto(out *WeightedSumRankingConfig) {
	*out = *in
	if in.Terms != nil {
		in, out := &in.Terms, &out.Terms
		*out = make([]WeightedSumTerm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeightedSumRankingConfig.
func (in *WeightedSumRankingConfig) DeepCopy() *WeightedSumRankingConfig {
	if in == nil {
		return nil
	}
	out := new(WeightedSumRankingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeightedSumTerm) DeepCopyInto(out *WeightedSumTerm) {
	*out = *in
	out.Weight = in.Weight.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeightedSumTerm.
func (in *WeightedSumTerm) DeepCopy() *WeightedSumTerm {
	if in == nil {
		return nil
	}
	out := new(WeightedSumTerm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WindowAggregateSignalConfig) DeepCopyInto(out *WindowAggregateSignalConfig) {
	*out = *in
	if in.RelativeWindow != nil {
		in, out := &in.RelativeWindow, &out.RelativeWindow
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Window != nil {
		in, out := &in.Window, &out.Window
		*out = new(TimeOfDayWindow)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WindowAggregateSignalConfig.
func (in *WindowAggregateSignalConfig) DeepCopy() *WindowAggregateSignalConfig {
	if in == nil {
		return nil
	}
	out := new(WindowAggregateSignalConfig)
	in.DeepCopyInto(out)
	return out
}
