{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "puller.fullname" . }}-metrics-cert
  labels:
    {{- include "puller.labels" . | nindent 4 }}
spec:
  secretName: {{ include "puller.fullname" . }}-metrics-tls
  issuerRef:
    {{- toYaml .Values.certManager.issuerRef | nindent 4 }}
  dnsNames:
    - {{ include "puller.fullname" . }}-metrics.{{ .Release.Namespace }}.svc
    - {{ include "puller.fullname" . }}-metrics.{{ .Release.Namespace }}.svc.cluster.local
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
{{- end }}
