apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "drop.fullname" . }}
  labels:
    {{- include "drop.labels" . | nindent 4 }}
rules:
  - apiGroups: ["drop.corewire.io"]
    resources: ["cachedimages"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["drop.corewire.io"]
    resources: ["cachedimages/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["drop.corewire.io"]
    resources: ["cachedimages/finalizers"]
    verbs: ["update"]
  - apiGroups: ["drop.corewire.io"]
    resources: ["cachedimagesets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["drop.corewire.io"]
    resources: ["cachedimagesets/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["drop.corewire.io"]
    resources: ["cachedimagesets/finalizers"]
    verbs: ["update"]
  - apiGroups: ["drop.corewire.io"]
    resources: ["pullpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["drop.corewire.io"]
    resources: ["discoverypolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["drop.corewire.io"]
    resources: ["discoverypolicies/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["drop.corewire.io"]
    resources: ["discoverypolicies/finalizers"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
