{{- if .Values.ui.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "drop.fullname" . }}-ui
  labels:
    {{- include "drop.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
{{- end }}
